language: generic

sudo: false
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - sourceline: 'ppa:keithw/glfw3'
    packages:
      - sbcl
      - time
      - autoconf
      - automake
      - autogen
      - autopoint
      - libncurses-dev
      - libx11-dev
      - libxpm-dev
      - libgtk2.0-dev
      - zlib1g-dev
      - libpcre3-dev
      - libcurl4-gnutls-dev
      - libssl-dev
      - libgcrypt-dev
      - libglfw3-dev
      - libtool
      - liblzma-dev
      - texinfo
      - xsel

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade openssl automake libgcrypt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install autoconf automake sbcl gettext pcre openssl libtool gnu-sed glfw libgcrypt pkg-config xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link gettext --force; fi

script:
  - cd build
  - ./build.sh